-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 10-12-2024 a las 14:54:39
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `portal`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `peliculas`
--

CREATE TABLE `peliculas` (
  `id` int(11) NOT NULL,
  `titulo` varchar(255) NOT NULL,
  `genero` varchar(100) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `trailer` varchar(255) NOT NULL,
  `img` varchar(255) DEFAULT NULL,
  `anio` int(11) DEFAULT NULL,
  `duracion` varchar(50) DEFAULT NULL,
  `temporadas` int(11) DEFAULT NULL,
  `elenco` text DEFAULT NULL,
  `tmg` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `peliculas`
--

INSERT INTO `peliculas` (`id`, `titulo`, `genero`, `descripcion`, `trailer`, `img`, `anio`, `duracion`, `temporadas`, `elenco`, `tmg`) VALUES
(1, 'Implacable (2024)', 'Acción, Thriller', 'Un exluchador de UFC, interpretado por Jake Gyllenhaal, llega a un bar conflictivo en Florida como el nuevo jefe de seguridad. Su misión de mantener el orden lo lleva a enfrentarse con peligrosos criminales locales, poniendo a prueba sus habilidades y su valentía en un lugar donde cada movimiento cuenta. La adrenalina y el suspenso crecen a medida que se adentra en un mundo que no perdona.', 'YuJhg4rzxaM', '/action/action1.png', 2024, '1h 32m', NULL, 'Liam Neeson, Monica Bellucci, Yaara Pelzig, Jonathan Tucker, J. Anthony Ramos', '/titulos/titulo100.png'),
(2, 'Furiosa: A mad max saga', ' Acción, Aventura, Ciencia Ficción', 'Esta película es una precuela de Mad Max: Fury Road, centrada en el personaje de Furiosa. La historia explora sus orígenes y cómo se convierte en la guerrera feroz que conocemos. Ambientada en un mundo postapocalíptico, la trama sigue su lucha por sobrevivir y encontrar su lugar en un entorno hostil, lleno de conflictos y traiciones.', 'wizMSLWBIrk', '/action/action2.png', 2024, '2h 28m', NULL, 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke, Nathan Jones, McNelly', '/titulos/titulo102.png'),
(3, 'Duro de Matar ', 'Acción, Thriller', 'John McClane, un oficial de policía de Nueva York, se encuentra atrapado en un rascacielos de Los Ángeles tomado por un grupo de terroristas durante una fiesta de Navidad. Mientras los rehenes son amenazados, McClane debe usar su ingenio y habilidades para salvar a los cautivos y detener al líder criminal, enfrentándose a peligros mortales en un juego del gato y el ratón que desafía la lógica y la gravedad.', 'jaJuwKCmJbY', '/action/action3.png', 1988, '2 horas y 12 minutos', NULL, 'Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason, William Atherton', '/titulos/titulo103.png'),
(4, 'El Caballero de la Noche', ' Acción, Thriller, Superhéroes', ' Batman se enfrenta a su enemigo más mortal, el Joker, en una batalla por el alma de Gotham City. Mientras el caos y la locura se desatan, el caballero oscuro debe lidiar con sus propios límites éticos y su identidad, al tiempo que busca mantener la paz en una ciudad al borde del colapso. La película explora temas de justicia, moralidad y la delgada línea entre héroes y villanos.', 'kj7urtvmwrY', '/action/action4.png', 2008, '2 horas y 32 minutos', NULL, 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman, Maggie Gyllenhaal, Morgan Freeman', '/titulos/titulo104.png'),
(5, 'John Wick', ' Acción, Thriller', 'Tras la muerte de su esposa, John Wick, un exasesino a sueldo, se ve obligado a regresar al mundo del crimen cuando unos delincuentes roban su auto y matan a su perro, un regalo de su difunta esposa. Impulsado por la venganza, Wick desata su implacable habilidad de combate en una búsqueda para recuperar lo que le fue arrebatado. A medida que avanza, se enfrenta a antiguos enemigos y nuevas amenazas, demostrando que no se puede subestimar a un hombre con nada que perder.', 'jbeRIvRRxdE', '/action/action5.png', 2014, '1 hora y 41 minutos', NULL, 'Keanu Reeves, Willem Dafoe, Alfie Allen, Ian McShane, Michael Nyqvist, Adrianne Palicki', '/titulos/titulo105.png'),
(6, 'Gladiador', 'Acción, Drama, Histórico', 'En la antigua Roma, el general Maximus es traicionado y reducido a la esclavitud. Impulsado por el deseo de venganza, se convierte en un gladiador y lucha en la arena, buscando recuperar su honor y vengar la muerte de su familia. A medida que se enfrenta a poderosos adversarios, Maximus también desafía la corrupción del imperio, convirtiéndose en un símbolo de resistencia. Su viaje épico explora temas de lealtad, traición y la lucha por la libertad.', 'lsDdsvKVbMo', '/action/action6.png', 2002, '2 horas y 35 minutos', NULL, 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Richard Harris, Djimon Hounsou', '/titulos/titulo106.png'),
(7, '\r\nMatrix 1', 'Ciencia Ficción, Acción', 'En un futuro distópico, el programador Thomas Anderson, conocido como Neo, descubre que el mundo que conoce es una simulación llamada \"Matrix\", creada por máquinas que mantienen a la humanidad bajo control. Guiado por Morfeo y Trinity, Neo se une a la lucha contra las máquinas para liberar a la humanidad. A medida que desentraña la verdad, se convierte en el elegido, enfrentándose a los peligros del sistema y a los agentes que intentan detenerlo.', 'Pl_H2Lmjn6k', '/action/action7.png', 1999, '2 horas y 16 minutos', NULL, 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Joe Pantoliano', '/titulos/titulo107.png'),
(8, '\r\nTerminator', 'Ciencia Ficción, Acción', 'En el año 1984, un cyborg conocido como el Terminator es enviado del futuro para asesinar a Sarah Connor, la madre del futuro líder de la resistencia humana contra las máquinas. Un soldado llamado Kyle Reese también es enviado para protegerla. Mientras Sarah lucha por entender su destino, los dos deben enfrentarse al implacable Terminator en una carrera contra el tiempo para alterar el futuro y salvar a la humanidad de la inminente guerra de las máquinas.', 'tMqGy1J0y6E', '/action/action8.png', 1984, '1 hora y 47 minutos', NULL, 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn, Paul Winfield, Lance Henriksen', '/titulos/titulo108.png'),
(9, 'El origen ', 'Ciencia Ficción, Acción', 'Dom Cobb es un ladrón especializado en extraer información de los sueños. Se le ofrece una oportunidad de redención: realizar \"inception\", introducir una idea en la mente de un objetivo. Junto a un equipo de expertos, Cobb se adentra en capas de sueños complejos y peligrosos, enfrentándose a sus propios demonios y a la naturaleza inestable de la realidad. La película explora los límites de la mente y la percepción, llevando al espectador a un viaje alucinante.', 'BZOMKZ0AwC8', '/action/action9.png', 2010, ' 2 horas y 28 minutos', NULL, 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Cillian Murphy, Marion Cotillard, Michael Caine', '/titulos/titulo109.png'),
(10, 'Los vengadores', 'Acción, Aventura, Superhéroes', 'Nick Fury, director de S.H.I.E.L.D., reúne a un grupo de superhéroes, incluidos Iron Man, Thor, Hulk, Capitán América y Black Widow, para enfrentar una amenaza inminente. Cuando Loki, el hermano adoptivo de Thor, intenta conquistar la Tierra con un ejército alienígena, estos héroes deben dejar de lado sus diferencias y trabajar juntos. La película explora temas de camaradería y sacrificio mientras los Vengadores luchan para salvar al mundo de la destrucción.', 'yNXfOOL8824', '/action/action10.png', 2012, '2 horas y 23 minutos', NULL, 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Tom Hiddleston, Samuel L. Jackson', '/titulos/titulo110.png'),
(11, '\r\n¿Qué Pasó Ayer?', 'Comedia, Aventura', 'Tras una noche de juerga en Las Vegas, un grupo de amigos se despierta con amnesia y se da cuenta de que el novio del hermano ha desaparecido. A medida que intentan reconstruir lo que sucedió, descubren una serie de situaciones absurdas y divertidas que les llevan a la hilarante búsqueda del novio perdido. La película explora las locuras de la amistad y las consecuencias inesperadas de una noche de celebración desenfrenada.', 'wnNgGp1KVWQ', '/comedia/comedia1.png', 2009, '1 hora y 40 minutos', NULL, 'Bradley Cooper, Zach Galifianakis, Ed Helms, Justin Bartha, Heather Graham, Mike Epps', '/titulos/titulo111.png'),
(12, 'Supercool', 'Comedia, Adolescente', 'Dos mejores amigos, que han estado en el lado equivocado de la popularidad, deciden cambiar su suerte y disfrutar de una noche épica de fiesta. Mientras intentan navegar por el mundo social de los adolescentes, se enfrentan a situaciones cómicas y absurdas que pondrán a prueba su amistad y su confianza. La película mezcla humor y experiencias adolescentes, destacando la importancia de ser uno mismo en medio de las presiones sociales.', 'b8ht6ObDlyQ', '/comedia/comedia2.png', 2007, '1 hora y 53 minutos', NULL, 'Jonah Hill, Michael Cera, Seth Rogen, Bill Hader, Emma Stone, Christopher Mintz-Plasse', '/titulos/titulo112.png'),
(13, 'Hechizo del Tiempo', 'Comedia, Fantasía, Romance', '', 'GncQtURdcE4&t=7s', '/comedia/comedia3.png', 1993, '1 hora y 41 minutos', NULL, 'Bill Murray, Andie MacDowell y Chris Elliott.\n\n', '/titulos/titulo113.png'),
(14, 'Tonto y re tonto 1', 'Comedia, Aventura', 'Lloyd y Harry, dos amigos poco inteligentes, se embarcan en un viaje a Aspen para devolver un maletín perdido que contiene dinero. A lo largo de su travesía, sus torpezas y decisiones absurdas crean situaciones hilarantes, mientras intentan hacer lo correcto. La película combina el humor físico con la comedia de errores, mostrando cómo dos \"idiotas\" pueden, de manera inesperada, encontrar el camino hacia la amistad y la aventura.', 'l13yPhimE3o', '/comedia/comedia4.png', 1994, '1 hora y 47 minutos', NULL, 'Jim Carrey, Jeff Daniels, Lauren Holly y Mike Starr.', '/titulos/titulo114.png'),
(15, 'Hermanastros', 'Comedia', 'Dos hombres con vidas muy diferentes, que se convierten en hermanastros tras el matrimonio de sus padres, se ven obligados a convivir. Su relación comienza con tensiones y rivalidades, pero a medida que se enfrentan a situaciones cómicas, desarrollan un vínculo inesperado. La película explora la dinámica familiar y cómo las diferencias pueden superarse a través del entendimiento y la amistad, todo mientras se desatan risas y locuras a lo largo de su convivencia.', 'JJvgsnQ4pmo', '/comedia/comedia5.png', 2008, '1 hora y 38 minutos', NULL, 'Will Ferrell, John C. Reilly, Mary Steenburgen y Richard Jenkins.', '/titulos/titulo115.png'),
(16, 'El reportero: La leyenda de Ron Burgundy', 'Comedia', 'En la década de 1970, Ron Burgundy es un famoso presentador de noticias de San Diego que se enfrenta a la llegada de una periodista femenina en un mundo dominado por hombres. A medida que su rivalidad y tensiones aumentan, Ron y su equipo se ven envueltos en una serie de situaciones absurdas y divertidas. La película parodia el mundo de las noticias, explorando temas de machismo y competencia en un tono hilarante y exagerado.', 'QvJ1K0_JzFI', '/comedia/comedia6.png', 2004, '1 hora y 34 minutos', NULL, 'Will Ferrell, Christina Applegate, Steve Carell y Paul Rudd.', '/titulos/titulo116.png'),
(17, 'Mi Pobre Angelito', 'Comedia, Familiar', 'Kevin McCallister, un niño de ocho años, es olvidado por su familia cuando se van de vacaciones a París. Al principio, disfruta de la libertad, pero pronto se enfrenta a dos torpes ladrones que intentan robar su casa. Usando su ingenio y una serie de trampas ingeniosas, Kevin protege su hogar mientras aprende sobre la familia y la responsabilidad. La película combina humor y ternura, convirtiéndola en un clásico navideño.', 'zoVUYHPMM', '/comedia/comedia7.png', 1990, '1 hora y 43 minutos', NULL, 'Macaulay Culkin, Joe Pesci, Daniel Stern, John Heard y Catherine O\'Hara.', '/titulos/titulo22.png'),
(18, 'Damas en Guerra', 'Comedia, Guerra', 'En esta comedia, dos mejores amigas, Annie y Lillian, se embarcan en la locura de planear una boda. A medida que las tensiones aumentan entre las damas de honor, surgen rivalidades y situaciones hilarantes. Con un enfoque en la amistad y las complicaciones que surgen en el proceso de planificación, la película mezcla humor y emociones mientras las protagonistas enfrentan los desafíos de ser damas de honor y amigas al mismo tiempo.', 'NQuoFfRpdSo', '/comedia/comedia8.png', 2011, '2 horas y 5 minutos', NULL, 'Kristen Wiig, Maya Rudolph, Melissa McCarthy y Rose Byrne.', '/titulos/titulo118.png'),
(19, 'Un Experto en Diversiones', 'Comedia, Familiar', 'Este film sigue a un exitoso planificador de fiestas que se encuentra en un dilema cuando su propia vida personal comienza a desmoronarse. Mientras intenta impresionar a una madre soltera y ganar el corazón de su hija, enfrenta situaciones cómicas y lecciones sobre la paternidad. La película combina humor con momentos entrañables, mostrando que la verdadera diversión y conexión vienen de ser auténtico y valorar a la familia.', 'sQmItYCzdlA', '/comedia/comedia9.png', 1986, '1 hora y 33 minutos', NULL, 'Matthew Broderick, Alan Ruck, Mia Sara, Jeffrey Jones y Jennifer Grey.', '/titulos/titulo119.png'),
(20, 'La Máscara', 'Comedia, Fantasía', 'Stanley Ipkiss, un tímido banquero, descubre una antigua máscara que transforma su vida. Al usarla, se convierte en un ser carismático y travieso con habilidades sobrehumanas. Sin embargo, sus aventuras lo llevan a enfrentarse con criminales y a buscar el amor. La película mezcla acción, humor y efectos especiales innovadores, explorando temas de identidad y autoconfianza a través de un enfoque cómico y extravagante.', '3g7fbQHkYI0', '/comedia/comedia10.png', 1994, '1 hora y 41 minutos', NULL, 'Jim Carrey, Cameron Diaz, Peter Riegert y Mike Starr.', '/titulos/titulo2.png'),
(21, 'Indiana Jones y el Arca Perdida', 'Aventura, Acción', 'El arqueólogo y aventurero Indiana Jones es reclutado por el gobierno de EE. UU. para encontrar el Arca de la Alianza antes de que los nazis la consigan. A medida que se enfrenta a trampas antiguas, rivalidades y peligros mortales, Indiana demuestra su ingenio y valentía. La película combina acción trepidante, humor y elementos históricos, estableciendo a Indiana Jones como un ícono del cine de aventura.', 'ceMf9xtDA6U', '/aventura/aventure1.png', 1981, '1 hora y 55 minutos', NULL, 'Harrison Ford, Karen Allen, Paul Freeman y Ronald Lacey.', '/titulos/titulo121.png'),
(22, 'El Señor de los Anillos: La Comunidad del Anillo', 'Fantasía, Aventura', 'En la Tierra Media, un hobbit llamado Frodo recibe la tarea de destruir un poderoso anillo que puede controlar a todos. Acompañado por un grupo diverso de aliados, incluyendo humanos, elfos y enanos, inicia un peligroso viaje para llegar al Monte del Destino. A medida que enfrentan a fuerzas oscuras y desafíos mortales, la película explora temas de amistad, sacrificio y la lucha entre el bien y el mal, todo en un impresionante mundo de fantasía.', 'iFOucwxKRFE', '/aventura/aventure2.png', 2001, '2 horas y 58 minutos', NULL, 'Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin, Orlando Bloom y Cate Blanchett.', '/titulos/titulo122.png'),
(23, 'Piratas del Caribe: La Maldición de la Perla Negra', 'Aventura, Fantasía', 'El Capitán Jack Sparrow, un pirata carismático, se une a Will Turner para rescatar a la hija del gobernador, Elizabeth Swann, quien ha sido secuestrada por una tripulación de piratas malditos. Mientras navegan por mares peligrosos, enfrentan traiciones y aventuras sobrenaturales. La película combina acción trepidante, humor y elementos de fantasía, convirtiéndose en un clásico moderno que revitalizó el género de piratas en el cine.', 'tnx35Z4nWWc', '/aventura/aventure3.png', 2003, '2 horas y 23 minutos', NULL, 'Johnny Depp, Orlando Bloom, Keira Knightley y Geoffrey Rush.\n\n', '/titulos/titulo123.png'),
(24, 'Jurassic Park', 'Ciencia Ficción, Aventura', 'Un multimillonario crea un parque temático con dinosaurios clonados, pero cuando un grupo de invitados visita la isla, la seguridad falla. Los dinosaurios escapan, poniendo en peligro a todos. Con la ayuda de un grupo de expertos, los personajes deben encontrar la manera de sobrevivir mientras enfrentan a estos gigantes prehistóricos. La película combina efectos especiales innovadores con temas de ética en la ciencia, convirtiéndose en un clásico del cine que redefinió el género de aventuras.', 'dLDkNge_AhE', '/aventura/aventure4.png', 1993, '2 horas y 7 minutos', NULL, 'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough y Joseph Mazzello.', '/titulos/titulo124.png'),
(25, 'Los Goonies', 'Aventura, Comedia', 'Un grupo de niños de un vecindario enfrenta la posibilidad de perder sus hogares y decide embarcarse en una búsqueda del tesoro escondido de un pirata legendario, One-Eyed Willy. A medida que siguen un antiguo mapa, se encuentran con trampas, criaturas y un grupo de delincuentes. La película celebra la amistad y la aventura, convirtiéndose en un clásico de culto que captura la esencia de la infancia y la imaginación.', '02vTArP0yug', '/aventura/aventure5.png', 1985, ' 1 hora y 54 minutos', NULL, 'Sean Astin, Josh Brolin, Corey Feldman, Martha Plimpton y Ke Huy Quan.\n\n', '/titulos/titulo125.png'),
(26, 'El Hobbit: Un Viaje Inesperado', 'Fantasía, Aventura', 'Bilbo Bolsón, un hobbit tranquilo, es reclutado por el mago Gandalf y un grupo de enanos para recuperar su hogar y tesoros de un dragón llamado Smaug. A lo largo de su viaje, Bilbo enfrenta peligros y enemigos, descubre su valentía y encuentra el Anillo que cambiará su vida. La película captura la esencia de la aventura y la exploración en un mundo fantástico, ofreciendo tanto acción como momentos entrañables.', 'a3mELVgSHEc', '/aventura/aventure6.png', 2012, '2 horas y 49 minutos', NULL, 'Martin Freeman, Ian McKellen, Richard Armitage, Benedict Cumberbatch, Orlando Bloom, Cate Blanchett, Hugo Weaving', '/titulos/titulo126.png'),
(27, 'La Momia', 'Aventura, Fantasía', 'En 1923, un grupo de exploradores, liderado por Rick O\'Connell, despierta accidentalmente a la momia de Imhotep, un antiguo sacerdote egipcio que busca recuperar a su amada. A medida que la momia desata su venganza sobre quienes perturban su descanso, los personajes deben encontrar la manera de detenerlo antes de que cause un caos total. La película mezcla acción, humor y elementos sobrenaturales, convirtiéndose en un clásico moderno de aventuras.', 'CT6yWV9e4Ig', '/aventura/aventure7.png', 1999, '2 horas y 4 minutos', NULL, 'Brendan Fraser, Rachel Weisz, John Hannah, Arnold Vosloo, Kevin J. O\'Connor, Oded Fehr', '/titulos/titulo127.png'),
(28, 'Avatar', 'Ciencia Ficción, Aventura', 'En un futuro distante, Jake Sully, un exmarine, es enviado al planeta Pandora, donde los humanos buscan extraer un valioso mineral. Utilizando un cuerpo híbrido llamado \"avatar\", Jake se infiltra en la tribu nativa de los Na\'vi. A medida que se sumerge en su cultura y desarrolla una conexión con Neytiri, debe elegir entre su lealtad a la humanidad y su amor por Pandora. La película destaca la lucha por la naturaleza y la conexión entre las especies en un mundo visualmente deslumbrante.', 'g5deg0HgCmY', '/aventura/aventure8.png', 2009, '2 horas y 42 minutos', NULL, 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi, Matt Gerald', '/titulos/titulo128.png'),
(29, 'Jumanji: Bienvenidos a la Jungla', 'Aventura, Comedia', 'Cuatro adolescentes descubren un antiguo videojuego llamado Jumanji y son absorbidos por su mundo, convirtiéndose en sus avatares. Para escapar, deben completar una peligrosa misión mientras enfrentan criaturas salvajes y desafíos inesperados. Con la ayuda de sus nuevas habilidades y la colaboración entre ellos, aprenden sobre la amistad y el trabajo en equipo. La película combina acción emocionante con humor, ofreciendo una nueva perspectiva de la clásica historia de Jumanji.', 'leIrosWRbYQ', '/aventura/aventure9.png', 2017, '1 hora y 59 minutos', NULL, 'Dwayne Johnson, Kevin Hart, Jack Black, Karen Gillan, Nick Jonas, Bobby Cannavale', '/titulos/titulo129.png'),
(30, 'Viaje 2: La Isla Misteriosa', 'Aventura, Comedia', 'Sean Anderson recibe un mensaje de socorro de su abuelo, que se encuentra en una isla desconocida. Junto a un grupo inesperado, incluyendo a su nuevo padrastro, emprenden una aventura épica para encontrarlo. Enfrentándose a peligrosos animales y fenómenos naturales, deben usar su ingenio para sobrevivir y desentrañar los secretos de la isla. La película mezcla acción, humor y un sentido de aventura familiar, ofreciendo una experiencia divertida y emocionante.', 've_WAOdN3YU', '/aventura/aventure10.png', 2012, '1 hora y 34 minutos', NULL, 'Dwayne Johnson, Josh Hutcherson, Vanessa Hudgens, Luis Guzmán, Michael Caine', '/titulos/titulo130.png'),
(31, 'Star Wars: La Amenaza Fantasma', 'Ciencia Ficción, Aventura', 'En un tiempo de crisis, los Jedi Qui-Gon Jinn y su aprendiz Obi-Wan Kenobi son enviados a negociar con la Federación de Comercio, que ha bloqueado el planeta Naboo. Allí conocen a la joven reina Amidala y al niño Anakin Skywalker, quien tiene un gran potencial. Juntos, deben enfrentarse a fuerzas oscuras que amenazan la paz en la galaxia. La película combina acción, política y elementos míticos, estableciendo las bases para la saga épica de Star Wars.', 'FZU43AoEhxQ', '/ciencia-fision/ciencia-fision1.png', 1999, ' 2 horas y 16 minutos', NULL, 'Liam Neeson, Ewan McGregor, Natalie Portman, Jake Lloyd, Ian McDiarmid, Samuel L. Jackson, Pernilla August', '/titulos/titulo131.png'),
(32, 'Elysium', 'Ciencia Ficción, Acción', 'En un futuro distópico, la Tierra está superpoblada y empobrecida, mientras que la élite vive en la lujosa estación espacial Elysium, donde la salud y la inmortalidad son accesibles. Max, un hombre de clase trabajadora, se encuentra con un desafío: debe infiltrarse en Elysium para salvar su vida. Con la ayuda de aliados inesperados, enfrenta un sistema opresivo y lucha por la igualdad y la justicia. La película mezcla acción intensa con comentarios sociales sobre la desigualdad.', '1XbXKEEonbE', '/ciencia-fision/ciencia-fision2.png', 2013, '1 hora y 49 minutos', NULL, 'Matt Damon, Jodie Foster, Sharlto Copley, Alice Braga, Diego Luna, Wagner Moura', '/titulos/titulo132.png'),
(33, 'Los Juegos del Hambre', 'Ciencia Ficción, Aventura', ' En un futuro distópico, Panem está dividido en 12 distritos, y cada año se celebran los Juegos del Hambre, un brutal torneo donde jóvenes luchan a muerte. Katniss Everdeen se ofrece como tributo en lugar de su hermana. Mientras navega por la competencia, debe enfrentarse a desafíos mortales y descubrir el significado de la resistencia. La película combina acción, intriga política y temas de supervivencia, convirtiéndose en un fenómeno cultural que aborda la lucha contra la opresión.', '_8Ktfs2mBDY', '/ciencia-fision/ciencia-fision3.png', 2012, '2 horas y 22 minutos', NULL, 'Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Stanley Tucci, Donald Sutherland', '/titulos/titulo133.png'),
(34, 'La Llegada', 'Ciencia Ficción, Drama', 'Cuando misteriosas naves espaciales aterrizan en la Tierra, la lingüista Louise Banks es reclutada para comunicarse con los extraterrestres. A medida que desentraña su lenguaje, descubre una nueva forma de percepción del tiempo y la realidad. La película explora temas de comunicación, amor y la naturaleza del tiempo, llevándola a una profunda reflexión sobre la vida y la pérdida. Con una narrativa no lineal y visualmente impactante, \"La Llegada\" desafía las convenciones del género de ciencia ficción.', 'uWs5lsWXLbo', '/ciencia-fision/ciencia-fision4.png', 2016, '1 hora y 56 minutos', NULL, 'Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg, Tzi Ma', '/titulos/titulo134.png'),
(35, 'Distrito 9', 'Ciencia Ficción, Acción', 'En Johannesburgo, Sudáfrica, extraterrestres han sido forzados a vivir en condiciones de chabolas tras su llegada a la Tierra. Cuando un funcionario de la corporación MNU se expone a una sustancia alienígena, comienza a transformarse y a experimentar la discriminación que sufren los extraterrestres. A medida que busca respuestas, se convierte en un fugitivo y se ve obligado a confrontar cuestiones de humanidad y xenofobia. La película combina acción intensa con críticas sociales sobre la segregación.', 'Ev9J2lS1IYg', '/ciencia-fision/ciencia-fision5.png', 2009, '1 hora y 52 minutos', NULL, 'Sharlto Copley, Jason Cope, David James, Vanessa Haywood, William Allen Young', '/titulos/titulo135.png'),
(36, 'Asesinos del Futuro', 'Ciencia Ficción, Acción', 'En un futuro distópico, el crimen ha alcanzado niveles insostenibles, y los gobiernos han implementado un sistema de justicia basado en la eliminación de objetivos. Un grupo de asesinos es enviado al pasado para eliminar a aquellos que amenazan la estabilidad del futuro. Sin embargo, uno de ellos comienza a cuestionar su misión y el verdadero significado de la moralidad. La película explora temas de libre albedrío y la naturaleza de la justicia, combinando acción intensa con reflexiones filosóficas.', 'mpUeCUxRgMw', '/ciencia-fision/ciencia-fision6.png', 2012, '1 hora y 58 minutos', NULL, ' Joseph Gordon-Levitt, Bruce Willis, Emily Blunt, Jeff Daniels, Paul Dano', '/titulos/titulo136.png'),
(37, 'Inteligencia Artificial', 'Ciencia Ficción, Drama', 'En un futuro donde los robots son comunes, un niño robot llamado David es programado para amar incondicionalmente. Tras ser abandonado por su familia, David emprende un viaje para volverse humano y encontrar su lugar en un mundo que no lo acepta. La película explora temas de amor, pérdida y la naturaleza de la humanidad. Visualmente impactante y emocionalmente resonante, es una reflexión profunda sobre la inteligencia artificial y el deseo.', 'BQ2iMHFMmCk', '/ciencia-fision/ciencia-fision7.png', 2001, '2 horas y 26 minutos', NULL, 'Haley Joel Osment, Jude Law, Frances O\'Connor, William Hurt, Brendan Gleeson', '/titulos/titulo137.png'),
(38, 'Hijos de los Hombres', 'Ciencia Ficción, Drama', '', 'T63mf2SrWTY', '/ciencia-fision/ciencia-fision8.png', 2006, '1 hora y 49 minutos', NULL, 'Clive Owen, Julianne Moore, Michael Caine, Chiwetel Ejiofor y Clare-Hope Ashitey.', '/titulos/titulo138.png'),
(39, 'El Planeta de los Simios: Confrontación', 'Ciencia Ficción, Acción', 'En un mundo post-apocalíptico, los simios, liderados por César, han formado una sociedad próspera, mientras que los humanos, diezmados por un virus, luchan por sobrevivir. Cuando un grupo humano se cruza con los simios, se desata un conflicto que pone a prueba la paz entre ambas especies. La película aborda temas de liderazgo, moralidad y la lucha por la supervivencia, ofreciendo una reflexión sobre la naturaleza del poder y la guerra.', 'gZiHrxeKdGo', '/ciencia-fision/ciencia-fision9.png', 2014, '2 horas y 10 minutos', NULL, 'Andy Serkis, Jason Clarke, Gary Oldman, Keri Russell, Toby Kebbell y Kodi Smit-McPhee.', '/titulos/titulo21.png'),
(40, 'Interestelar', 'Ciencia Ficción, Aventura', 'En un futuro cercano, la Tierra se enfrenta a la extinción debido a la falta de recursos. Cooper, un piloto y ex ingeniero de la NASA, es reclutado para una misión intergaláctica en busca de un nuevo hogar para la humanidad. Mientras viaja a través de agujeros de gusano y enfrenta desafíos cósmicos, la película explora temas de amor, sacrificio y la naturaleza del tiempo, todo mientras busca salvar a la humanidad. Un viaje visual y emocional hacia lo desconocido.', 'LYS2O1nl9iM', '/ciencia-fision/ciencia-fision10.png', 2014, '2 horas y 49 minutos', NULL, ' Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine y Matt Damon.', '/titulos/titulo7.png'),
(41, 'Zodiaco', 'Suspense, Crimen', 'Basada en hechos reales, \"Zodiaco\" sigue la obsesiva búsqueda de un periodista y un detective para identificar al infame asesino del Zodiaco, que aterrorizó el área de la bahía de San Francisco en los años 60 y 70. A medida que se involucran más en el caso, se enfrentan a la frustración de una investigación sin resolver y a la locura que desata el misterio. La película explora temas de obsesión, paranoia y la búsqueda de la verdad.', 'QI1jajUjzMw', '/misterio/misterio1.png', 2007, '2 horas y 37 minutos', NULL, 'Jake Gyllenhaal, Robert Downey Jr., Mark Ruffalo, Anthony Edwards y Chloë Sevigny.', '/titulos/titulo141.png'),
(42, 'Seven (Los Siete Pecados Capitales)', 'Suspense, Crimen', 'En una ciudad oscura y decadente, dos detectives, el novato David Mills y el veterano William Somerset, persiguen a un asesino en serie que basa sus crímenes en los siete pecados capitales. A medida que desentrañan el misterio, se enfrentan a la naturaleza del mal y a su propia moralidad. La atmósfera tensa y el giro final impactante han convertido a esta película en un clásico del género.', 'xhzBmjdehPA', '/misterio/misterio2.png', 1995, '2 horas y 7 minutos', NULL, 'Brad Pitt, Morgan Freeman, Gwyneth Paltrow y Kevin Spacey.', '/titulos/titulo142.png'),
(43, 'La Isla Siniestra', 'Suspense, Misterio, Thriller', 'En 1954, el Marshal Teddy Daniels y su compañero llegan a un hospital psiquiátrico en una remota isla para investigar la desaparición de una paciente. A medida que profundizan en el caso, se encuentran con secretos inquietantes y una atmósfera de paranoia. La historia explora temas de locura, trauma y la percepción de la realidad, llevando a un clímax sorprendente que pone en duda todo lo que creían saber.', '95z6iWCjEgc', '/misterio/misterio3.png', 2010, '2 horas y 18 minutos', NULL, 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley y Michelle Williams.', '/titulos/titulo143.png'),
(44, 'Los Otros', 'Suspense, Terror, Misterio', 'Ambientada en 1945, la película sigue a Grace, una madre que vive en una mansión aislada con sus dos hijos, quienes padecen fotosensibilidad. A medida que extraños sucesos comienzan a ocurrir en la casa, Grace se convence de que la vivienda está habitada por espíritus. La trama juega con la percepción de la realidad y el miedo a lo desconocido, culminando en un giro impactante que desafía las expectativas del espectador.', 'vON5kiGf1TI', '/misterio/misterio4.png', 2001, '1 hora y 44 minutos', NULL, 'Nicole Kidman, Fionnula Flanagan, Christopher Eccleston, Alakina Mann y James Bentley.', '/titulos/titulo144.png'),
(45, 'Río Místico\r\n', 'Drama, Misterio, Thriller', 'La historia sigue a un grupo de amigos que se reúnen para recordar un trágico evento de su infancia. A medida que exploran los recuerdos, se revelan secretos oscuros y relaciones complejas, llevándolos a confrontar el pasado. La trama mezcla elementos de suspenso con una profunda exploración emocional, cuestionando la naturaleza de la memoria y la culpa. La atmósfera cargada de tensión y el desarrollo de los personajes crean una narrativa cautivadora.', 'iCYoGicgruU', '/misterio/misterio5.png', 2003, '2 horas y 18 minutos', NULL, 'Sean Penn, Tim Robbins, Kevin Bacon, Laurence Fishburne y Marcia Gay Harden.', '/titulos/titulo145.png'),
(46, 'Prisioneros\r\n', 'Drama, Suspense, Thriller', 'Cuando dos niñas desaparecen, un padre desesperado, Keller Dover, toma medidas drásticas para encontrarlas, sospechando de un joven que fue interrogado pero liberado. A medida que la investigación se complica, las tensiones aumentan y se plantean preguntas morales sobre la justicia y la desesperación. La película profundiza en el dilema entre la ley y la venganza, presentando un thriller oscuro que examina los límites de la paternidad y la ética.', 'AiN1ahjVb3Y', '/misterio/misterio6.png', 2013, '2 horas y 33 minutos', NULL, 'Hugh Jackman, Jake Gyllenhaal, Viola Davis, Maria Bello, Terrence Howard y Melissa Leo.', '/titulos/titulo146.png'),
(47, 'Contra Tiempo', 'Thriller, Misterio', 'Un exitoso empresario se despierta en el coche de su amante, cubierto de sangre y sin recordar cómo llegó allí. A medida que intenta reconstruir los eventos que llevaron a su situación, se ve atrapado en una red de engaños y mentiras. La película juega con el tiempo y la percepción, presentando giros inesperados que mantienen al espectador en suspense hasta el final. Cada revelación desafía las creencias del protagonista y la verdad detrás de la tragedia.', '4HOrjGQhpV4', '/misterio/misterio7.png', 2016, '1 hora y 46 minutos', NULL, 'Mario Casas, Ana Wagener, José Coronado, Bárbara Lennie y Francesc Orella.', '/titulos/titulo147.png'),
(48, 'El Cuerpo', 'Thriller, Misterio\r\n', 'La trama gira en torno a la misteriosa desaparición del cadáver de una mujer que fue hallado en la morgue. Un detective y un médico forense se ven inmersos en una investigación que revela secretos oscuros y giros inesperados. A medida que profundizan, descubren una red de mentiras que desafía sus percepciones de la realidad y la moralidad. La película combina elementos de suspense y drama, manteniendo a la audiencia intrigada hasta el desenlace.', 'L0SztFfJv58', '/misterio/misterio8.png', 2012, '1 hora y 48 minutos', NULL, 'José Coronado, Hugo Silva, Belén Rueda y Aura Garrido.', '/titulos/titulo148.png'),
(49, 'La Ventana Indiscreta', 'Suspense, Thriller', 'Un fotógrafo confinado a su apartamento por una pierna rota comienza a observar a sus vecinos a través de su ventana. Pronto, sospecha que uno de ellos ha cometido un asesinato. A medida que se obsesiona con lo que ve, se involucra en un misterio peligroso que pone a prueba su cordura y su vida. La película explora temas de voyeurismo y moralidad, mientras mantiene una tensión constante hasta su impactante desenlace.', 'C3RPBQ8gSfg', '/misterio/misterio9.png', 1954, '1 hora y 52 minutos', NULL, 'James Stewart, Grace Kelly, Wendell Corey y Thelma Ritter.\r\n\r\n', '/titulos/titulo149.png'),
(50, 'Amnesia', 'Thriller, Misterio', 'Un hombre sufre de amnesia y se encuentra atrapado en una red de engaños y secretos oscuros. A medida que intenta recuperar sus recuerdos, se enfrenta a un pasado aterrador que lo involucra en un juego mortal. La narrativa se desarrolla a través de giros sorprendentes y revela la complejidad de la identidad y la memoria. La película mantiene una atmósfera tensa, cuestionando qué es real y qué es fabricado, culminando en un desenlace impactante.', '5NWcsPBJJbU', '', 2000, '1 hora y 53 minutos', NULL, 'Guy Pearce, Carrie-Anne Moss y Joe Pantoliano.', '/titulos/titulo150.png'),
(51, 'El Exorcista', 'Terror, Suspense', 'Una madre desesperada busca ayuda cuando su hija, Regan, comienza a mostrar comportamientos extraños y aterradores. Al descubrir que su hija está poseída por un demonio, recurre a un sacerdote para realizar un exorcismo. La película explora temas de fe, el bien contra el mal y la fragilidad de la mente humana, creando un ambiente de terror psicológico. Su impactante narrativa y escenas icónicas han dejado una huella duradera en el género del terror.', '7iCJssW8XiI', '/terror/terror1.png', 1973, '2 horas y 2 minutos', NULL, 'Linda Blair, Ellen Burstyn, Max von Sydow, Jason Miller', '/titulos/titulo151.png'),
(52, 'El Conjuro', 'Terror, Suspense', 'Basada en hechos reales, la película sigue a los investigadores paranormales Ed y Lorraine Warren mientras ayudan a una familia atormentada por una presencia oscura en su granja. A medida que los fenómenos sobrenaturales se intensifican, los Warren deben enfrentarse a fuerzas malignas para salvar a la familia y, posiblemente, a sí mismos. La historia combina elementos de terror psicológico con leyendas de exorcismos, ofreciendo una experiencia escalofriante y tensa que mantiene al espectador al borde de su asiento.', 're-COVREAoI', '/terror/terror2.png', 2013, '1 hora y 52 minutos', NULL, 'Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston', '/titulos/titulo152.png'),
(53, 'Psicosis', 'Terror, Suspense', 'La historia sigue a Marion Crane, quien roba una gran suma de dinero y se detiene en un motel aislado regentado por el extraño Norman Bates. A medida que la trama avanza, se revela la compleja relación entre Norman y su madre, creando un ambiente de tensión y terror psicológico. La película es famosa por su icónica escena de la ducha y su exploración de la locura, estableciendo nuevos estándares en el género del horror.', 'inwqMQIFrrA', '/terror/terror3.png', 1960, '1 hora y 49 minutos', NULL, 'Anthony Perkins, Janet Leigh, Vera Miles, John Gavin', '/titulos/titulo153.png'),
(54, 'it', 'Terror, Suspense', 'En la pequeña ciudad de Derry, un grupo de niños se enfrenta a una entidad sobrenatural que toma la forma de Pennywise, un aterrador payaso. A medida que el grupo, conocido como \"Los Perdedores\", se une para enfrentar sus miedos, descubren que Pennywise se alimenta de la angustia infantil y aparece cada 27 años. La película combina elementos de horror psicológico con la lucha por la amistad y la valentía, creando una atmósfera de tensión y miedo que perdura.', 'pxgsAXKzhSE', '/terror/terror4.png', 2017, '2 horas y 15 minutos', NULL, 'Bill Skarsgård, Jaeden Martell, Finn Wolfhard, Sophia Lillis, Jack Dylan Grazer', '/titulos/titulo19.png'),
(55, 'El Legado del Diablo', 'Terror, Suspense', 'Tras la muerte de su madre, Annie, una artista, descubre oscuros secretos familiares que la llevan a confrontar fuerzas malignas que han acechado a su familia por generaciones. A medida que las manifestaciones sobrenaturales se intensifican, Annie y su familia luchan por entender la herencia de terror que han heredado. La película explora temas de trauma, duelo y el impacto de los secretos familiares, creando una atmósfera inquietante que mantiene al espectador en vilo.', 'SJrssIEzTrI', '/terror/terror5.png', 2018, '2 horas y 7 minutos', NULL, 'Toni Collette, Alex Wolff, Milly Shapiro, Gabriel Byrne', '/titulos/titulo155.png'),
(56, 'Actividad Paranormal', 'Terror, Suspense', 'Esta película de formato found footage sigue a una joven pareja que comienza a experimentar fenómenos extraños en su hogar. Decididos a capturar la evidencia de lo sobrenatural, instalan cámaras en su casa, solo para descubrir que una entidad malévola está acechando sus vidas. A medida que los sucesos se vuelven más inquietantes, la tensión crece y la relación de la pareja se pone a prueba. La película es conocida por su enfoque innovador y su atmósfera escalofriante, que la convierte en un clásico del terror moderno.', 'gbYt5U3zL-M', '/terror/terror6.png', 2007, '1 hora y 26 minutos', NULL, 'Katie Featherston, Micah Sloat, Mark Fredrichs, Amber Armstrong', '/titulos/titulo56.png'),
(57, 'La Masacre de Texas', 'Terror, Suspense', 'Un grupo de amigos se dirige a Texas para visitar un cementerio, pero pronto se encuentran atrapados en una pesadilla cuando son acechados por Leatherface, un asesino enmascarado que pertenece a una familia canibal. A medida que intentan escapar, la brutalidad de la familia y la desesperación de los jóvenes crean una atmósfera de terror implacable. La película es un hito del género slasher, conocida por su crudeza y su impacto en la cultura del horror.', 'BkJzIG4QsYE', '/terror/terror7.png', 1974, '1 hora y 23 minutos', NULL, 'Marilyn Burns, Gunnar Hansen, Paul A. Partain, Edwin Neal', '/titulos/titulo157.png'),
(58, 'El Aro', 'Terror, Suspense', 'Una periodista investiga una misteriosa cinta de vídeo que provoca la muerte de quienes la ven en un plazo de siete días. Al ver la cinta, se sumerge en una carrera contra el tiempo para desentrañar el oscuro secreto detrás de la película y salvar su vida y la de su hijo. La atmósfera inquietante y los giros sorprendentes la convierten en un clásico del terror psicológico.', 'gmiG3txcgis', '/terror/terror8.png', 2002, '1 hora y 55 minutos', NULL, 'Naomi Watts, Martin Henderson, David Dorfman, Brian Cox', '/titulos/titulo158.png'),
(59, 'La Noche de Halloween\n', 'Terror, Suspense', 'En esta icónica película, un asesino en serie llamado Michael Myers escapa de un hospital psiquiátrico y regresa a su ciudad natal, donde comienza a acechar y matar a jóvenes. La adolescente Laurie Strode, interpretada por Jamie Lee Curtis, se convierte en su objetivo principal. Con un ambiente tenso y una atmósfera escalofriante, la película se ha convertido en un clásico del género slasher, influyendo en innumerables producciones posteriores.', 'sVBa5hNZFHM', '/terror/terror9.png', 1978, ' 1 hora y 31 minutos', NULL, 'Jamie Lee Curtis, Donald Pleasence, Nancy Kyes, P.J. Soles', '/titulos/titulo159.png'),
(60, 'Chucky', 'Terror, Suspense', 'En esta película de culto, un asesino en serie, Charles Lee Ray, transfiere su alma a una muñeca llamada \"Chucky\" para evadir la muerte. Cuando una madre le regala la muñeca a su hijo, Andy, Chucky comienza a desatar su sed de sangre, convirtiéndose en un aterrador enemigo. La combinación de horror y humor negro, junto con el carismático muñeco, ha hecho de esta película un referente del género de terror.', 'Nyr12mSlgTc', '/terror/terror10.png', 1988, '1 hora y 27 minutos', NULL, 'Catherine Hicks, Chris Sarandon, Alex Vincent, Brad Dourif (voz de Chucky)', '/titulos/titulo160.png'),
(61, 'Breaking Bad', 'Drama, Suspenso, Crimen', 'Walter White, un profesor de química diagnosticado con cáncer terminal, decide fabricar metanfetaminas para asegurar el futuro económico de su familia. Asociado con un antiguo estudiante, Jesse Pinkman, su transformación de profesor a despiadado capo de la droga pone en peligro su vida y la de sus seres queridos. Aclamada por su intensidad y desarrollo de personajes, esta serie explora hasta dónde puede llegar alguien cuando se enfrenta a decisiones extremas.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'mXd1zTwcQ18', '/series-accion/action1.png', 2008, NULL, 5, 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris', '/titulos/titulo18.png'),
(62, 'Vikingos\r\n', 'Drama histórico, Acción, Aventura', 'Inspirada en las sagas nórdicas, esta serie sigue la vida de Ragnar Lothbrok, un legendario guerrero vikingo, desde sus primeros saqueos hasta convertirse en rey. La historia explora las relaciones de Ragnar con su familia, su tribu, y su ambición por descubrir y conquistar nuevas tierras. Con épicas batallas y un enfoque en la cultura vikinga, la serie combina acción y drama en una representación intensa de la era vikinga y sus desafíos.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '0DZKZ0qktU4', '/series-accion/action2.png', 2013, NULL, 6, 'Travis Fimmel, Katheryn Winnick, Clive Standen, Gustaf Skarsgård, Alexander Ludwig', '/titulos/titulo162.png'),
(63, 'Grandes Héroes\r\n', 'Animación, Ciencia ficción, Aventura', 'Hiro y Baymax, junto con sus amigos, Wasabi, Honey Lemon, Go Go y Fred, unen fuerzas para formar el legendario grupo de superhéroes: Los 6 Grandes Héroes, para proteger su ciudad de una variada serie de villanos científicamente mejorados que intentan sembrar el caos y la confusión.', 'gZgre_WKDuk', '/series-accion/action3.png', 2017, NULL, 3, 'Ryan Potter, Scott Adsit, Jamie Chung, Damon Wayans Jr.', '/titulos/titulo163.png'),
(64, 'Dragon Ball Super', 'Acción, Aventura, Ciencia ficción, Animación', 'En esta continuación de \"Dragon Ball Z,\" Goku y sus amigos enfrentan nuevos desafíos que ponen a prueba sus límites, como la llegada de poderosos dioses, la amenaza de guerreros de otros universos y peligros inimaginables. Tras alcanzar niveles de poder inéditos, Goku, Vegeta y los demás luchan en épicos torneos para proteger su universo. La serie combina acción intensa con momentos de humor y sigue explorando temas de amistad y sacrificio.', 'giKGGDfT0DQ', '/series-accion/action4.png', 2015, NULL, 2, 'Masako Nozawa, Ryō Horikawa, Mayumi Tanaka', '/titulos/titulo23.png'),
(65, 'Ataque de Titanes\r\n', 'Acción, Aventura, Fantasía oscura, Animación', 'En un mundo asediado por gigantescos humanoides llamados Titanes, la humanidad vive dentro de enormes murallas para protegerse. La historia sigue a Eren Yeager y sus amigos, quienes se unen a la lucha contra los Titanes después de que su ciudad es invadida. A medida que se desvelan secretos sobre los Titanes y su origen, los protagonistas enfrentan dilemas morales y la lucha por la supervivencia. La serie es conocida por su intensa acción y profundas temáticas.', 'r9YVV0Pf6Tw', '/series-accion/action5.png', 2013, NULL, 4, 'Yûki Kaji, Marina Inoue, Josh Grelle, Trina Nishimura', '/titulos/titulo16.png'),
(66, 'Friends', 'Comedia, Romance', 'Esta icónica serie sigue las vidas de seis amigos en Nueva York: Ross, Rachel, Monica, Chandler, Joey y Phoebe. A través de risas, romances y desventuras, exploran los altibajos de la vida adulta mientras navegan por el amor, la amistad y la familia. Con diálogos memorables y personajes entrañables, \"Friends\" se ha convertido en un clásico de la televisión que continúa resonando con audiencias de todas las generaciones. Su humor y química entre el elenco son inigualables.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'ki6Mbtnl_9I', '/series-comedia/comedia1.png', 1994, NULL, 10, ' Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry, David Schwimmer', '/titulos/titulo166.png'),
(67, 'The Office\r\n', 'Comedia, Mockumentary', 'Esta serie sigue la vida cotidiana de los empleados de Dunder Mifflin, una empresa de papel en Scranton, Pennsylvania. Presentada en formato de falso documental, se centra en el humor incómodo y las interacciones absurdas entre personajes como el torpe jefe Michael Scott y la astuta asistente Pam. A medida que los empleados navegan por sus relaciones laborales y personales, \"The Office\" se ha convertido en un clásico, conocido por su ingenioso guion y su inolvidable elenco.', 'gO8N3L_aERg', '/series-comedia/comedia2.png', 2005, NULL, 9, 'Steve Carell, Rainn Wilson, John Krasinski, Jenna Fischer', '/titulos/titulo167.png'),
(68, 'Cars: Aventura en el camino\r\n', 'Animación, Aventura, Comedia', 'En esta secuela de \"Cars,\" Rayo McQueen se embarca en un nuevo viaje por carretera junto a sus amigos. La historia sigue sus aventuras mientras compite en una serie de carreras emocionantes, enfrentándose a nuevos desafíos y aprendiendo valiosas lecciones sobre la amistad y la perseverancia. Con un enfoque en el crecimiento personal y el trabajo en equipo, \"Cars: Aventura en el camino\" combina diversión y emoción en un entorno vibrante.', 'Yf7DHWOkxCc', '/series-comedia/comedia3.png', 2022, NULL, 1, 'Owen Wilson, Larry the Cable Guy, Michael Caine', '/titulos/titulo168.png'),
(69, 'El Show de Tom y Jerry', 'Animación, Comedia', 'Esta clásica serie animada sigue las interminables y cómicas persecuciones entre Tom, un gato doméstico, y Jerry, un astuto ratón. A pesar de sus constantes enfrentamientos, la serie presenta un humor slapstick visual que ha entretenido a generaciones. Cada episodio está lleno de ingeniosos trucos y travesuras, mostrando la lucha constante entre el cazador y la presa, con un estilo de animación vibrante y creativo que destaca por su calidad.', 'ML6LvPWDAM', '/series-comedia/comedia4.png', 1940, NULL, 7, 'William Hanna, Joseph Barbera (creadores)', '/titulos/titulo17.png'),
(70, 'Un Show Más', 'Animación, Comedia', 'Esta serie sigue las aventuras de dos amigos, Mordecai y Rigby, que trabajan como jardineros en un parque y frecuentemente se involucran en situaciones surrealistas y absurdas. Con un estilo humorístico y una animación vibrante, \"Un Show Más\" mezcla lo cotidiano con lo fantástico, creando historias hilarantes que desafían la lógica. La serie explora temas de amistad y madurez mientras los personajes navegan por los retos de la vida adulta, todo con un toque de locura y diversión.', 's1zrtqqfQsM', '/series-comedia/comedia5.png', 2010, NULL, 8, 'J.G. Quintel, William Salyers, Sam Marin', '/titulos/titulo170.png'),
(71, 'Gravity Falls\r\n', 'Animación, Aventura, Comedia, Misterio\r\n', 'La serie sigue a los gemelos Dipper y Mabel Pines, quienes pasan el verano con su tío Stan en el misterioso pueblo de Gravity Falls. A medida que exploran el bosque, descubren criaturas sobrenaturales y secretos ocultos, mientras Dipper intenta desentrañar el misterio de un diario enigmático. Con un equilibrio entre humor y momentos conmovedores, \"Gravity Falls\" ha capturado la imaginación de los espectadores, convirtiéndose en un favorito por su ingenio y narrativa intrigante.', 'yfUDIPUETUg', '/series-aventura/aventure1.png', 2012, NULL, 2, 'Jason Ritter, Kristen Schaal, Alex Hirsch', '/titulos/titulo171.png'),
(72, 'Stranger Things\r\n', 'Ciencia Ficción, Terror, Drama', 'Ambientada en la década de 1980, esta serie sigue a un grupo de niños en el pequeño pueblo de Hawkins, Indiana, que se enfrentan a fenómenos sobrenaturales y a una misteriosa entidad conocida como el Demogorgon. La desaparición de un niño y la llegada de una niña con habilidades psíquicas, llamada Eleven, desencadena una serie de eventos inquietantes. Con una mezcla de nostalgia, amistad y terror, \"Stranger Things\" explora la lucha entre el bien y el mal en un mundo lleno de secretos.', 'x7Yq9MJUqjY', '/series-aventura/aventure2.png', 2016, NULL, 4, 'Winona Ryder, David Harbour, Finn Wolfhard, Millie Bobby Brown', '/titulos/titulo12.png'),
(73, 'Lost\r\n', 'Aventura, Misterio, Drama, Ciencia Ficción', 'La serie sigue a los sobrevivientes de un accidente aéreo que se estrellan en una isla misteriosa. A medida que intentan sobrevivir, descubren que la isla tiene secretos oscuros y habilidades sobrenaturales. Cada episodio se centra en la historia de un personaje, revelando su pasado y sus luchas internas. \"Lost\" es conocida por su complejidad narrativa, tramas entrelazadas y giros inesperados, explorando temas de redención, supervivencia y la lucha entre el bien y el mal.', 'KTu8iDynwNc', '/series-aventura/aventure3.png', 2004, NULL, 6, 'Matthew Fox, Evangeline Lilly, Josh Holloway, Terry O\'Quinn', '/titulos/titulo173.png'),
(74, 'Avatar\r\n', 'Ciencia Ficción, Aventura, Fantasía', 'En el año 2154, un exmarine parapléjico, Jake Sully, es enviado a Pandora, una luna habitable con una rica biodiversidad y habitada por los Na\'vi. Jake participa en el programa Avatar, donde controla un cuerpo Na\'vi para infiltrarse en la comunidad y ayudar a los humanos a extraer valiosos recursos. A medida que se relaciona con los Na\'vi, Jake se enfrenta a un dilema moral sobre lealtades y su lugar en el conflicto entre humanos y nativos.', 'BPYW-_mF3LM', '/series-aventura/aventure4.png', 2005, NULL, 3, ' Zach Tyler Eisen, Mae Whitman, Jack DeSena, Dante Basco', '/titulos/titulo174.png');
INSERT INTO `peliculas` (`id`, `titulo`, `genero`, `descripcion`, `trailer`, `img`, `anio`, `duracion`, `temporadas`, `elenco`, `tmg`) VALUES
(75, 'Hora de Aventura\r\n', 'Animación, Aventura, Fantasía', 'La serie sigue las aventuras de Finn, un niño humano, y Jake, su mejor amigo y un perro con habilidades mágicas. Juntos, recorren el mundo de Ooo, enfrentando villanos, explorando reinos fantásticos y ayudando a quienes lo necesitan. Con un estilo único y un sentido del humor peculiar, \"Hora de Aventura\" combina elementos de acción, amistad y crecimiento personal, atrayendo tanto a niños como a adultos a través de sus historias creativas y emocionantes.', 'cWfAN_TwW0E', '/series-aventura/aventure5.png', 2010, NULL, 10, 'Jeremy Shada, John DiMaggio, Pendleton Ward (creador)', '/titulos/titulo11.png'),
(76, 'Rick y Morty\r\n', 'Animación, Ciencia Ficción, Comedia', 'La serie sigue las desventuras de Rick Sanchez, un científico loco, y su nieto Morty, quienes viajan a través de dimensiones y realidades paralelas. Con un humor oscuro y satírico, \"Rick y Morty\" explora temas complejos como la moralidad, la existencia y las relaciones familiares. A medida que enfrentan peligros y absurdos en su camino, la serie combina la comedia con reflexiones profundas, convirtiéndola en un fenómeno cultural que atrae a una audiencia diversa.', 'mD_NTkiOchU', '/series-ciencia-fision/ciencia-fision1.png', 2013, NULL, 7, 'Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke, Kari Wahlgren, Keith Ferguson\r\n', '/titulos/titulo14.png'),
(77, 'Star Wars: The Clone Wars\r\n', 'Animación, Aventura, Ciencia Ficción', 'Ambientada entre \"El Ataque de los Clones\" y \"La Venganza de los Sith\", la serie sigue las batallas de la República contra los separatistas y explora el desarrollo de personajes como Anakin Skywalker, Ahsoka Tano y Obi-Wan Kenobi. Con su mezcla de acción, drama y exploración de temas como la lealtad y el sacrificio, \"The Clone Wars\" profundiza en el conflicto y las relaciones interpersonales, enriqueciendo el universo de Star Wars.', 'SfxgMQ0QZFg', '/series-ciencia-fision/ciencia-fision2.png', 2008, NULL, 7, 'Matt Lanter, Ashley Eckstein, James Arnold Taylor, Dee Bradley Baker, Tom Kane, Matt Stone, Nika Futterman', '/titulos/titulo177.png'),
(78, 'Mundos Paralelos\r\n', 'Ciencia Ficción, Aventura', 'Esta serie explora la vida de un grupo de jóvenes que descubren la existencia de universos paralelos. A medida que investigan, se enfrentan a dilemas morales y a la complejidad de las decisiones que toman en diferentes realidades. Con una narrativa intrigante, \"Mundos Paralelos\" combina elementos de aventura, amistad y el impacto de las elecciones en el destino de cada personaje. La serie plantea preguntas sobre la naturaleza de la realidad y cómo nuestras decisiones nos moldean.', 'f3RU2Yg_7xc', '/series-ciencia-fision/ciencia-fision3.png', 2008, NULL, 5, 'Anna Torv, Joshua Jackson, John Noble, Lance Reddick, Jasika Nicole, Blair Brown', '/titulos/titulo178.png'),
(79, 'El Laboratorio de Dexter\r\n', 'Animación, Comedia, Ciencia Ficción', 'La serie sigue a Dexter, un niño prodigio con un laboratorio secreto lleno de inventos y experimentos. A menudo, se enfrenta a la frustrante interferencia de su hermana Dee Dee, quien arruina sus planes. A través de situaciones cómicas y aventuras científicas, \"El Laboratorio de Dexter\" combina humor con la curiosidad infantil, destacando la imaginación y la creatividad, mientras Dexter intenta proteger sus secretos y demostrar su genio en el mundo de la ciencia.', 'Ya3Q9OLk25g', '/series-ciencia-fision/ciencia-fision4.png', 1996, NULL, 4, 'Christine Cavanaugh, Jeffrey Tambor, Kath Soucie, Frank Welker, Eddie Deezen', '/titulos/titulo179.png'),
(80, 'Star Trek: Picard\r\n', 'Ciencia Ficción, Drama', 'La serie sigue al legendario Capitán Jean-Luc Picard, quien sale de su retiro para enfrentar un nuevo misterio que amenaza a la galaxia. A medida que se une a antiguos aliados y nuevos amigos, Picard explora temas de redención, lealtad y la lucha contra las sombras de su pasado. \"Star Trek: Picard\" rinde homenaje a la rica historia de \"Star Trek\" mientras ofrece una narrativa profunda y emocional que resonará tanto con los fanáticos de la saga como con nuevos espectadores.', 'xxHWh1n-qUU', '/series-ciencia-fision/ciencia-fision5.png', 2020, NULL, 3, 'Patrick Stewart, Alison Pill, Isa Briones, Michelle Hurd, Santiago Cabrera, Evan Evagora, Jeri Ryan, Brent Spiner, Jonathan Frakes', '/titulos/titulo180.png'),
(81, 'Death Note', 'Animación, Misterio, Thriller Psicológico', 'La serie sigue a Light Yagami, un estudiante brillante que descubre un cuaderno que le permite matar a cualquier persona cuyo nombre escriba en él. Con la intención de crear un mundo sin criminales, Light se convierte en un vigilante, pero su creciente poder atrae la atención de la policía y del astuto detective conocido como L. \"Death Note\" explora temas de justicia, moralidad y el conflicto entre el bien y el mal, manteniendo a los espectadores en tensión con giros inesperados y un juego mental intenso.', 'rZzG1C2hI8M', '/series-misterio/misterio1.png', 2006, NULL, 1, 'Mamoru Miyano, Noriko Hidaka, Kappei Yamaguchi, Alessandro Juliani, Brian Dobson', '/titulos/titulo181.png'),
(82, 'Dark', 'Ciencia Ficción, Misterio, Thriller', 'La serie alemana \"Dark\" explora la desaparición de varios niños en la pequeña ciudad de Winden, revelando oscuros secretos familiares y un complejo viaje a través del tiempo. A medida que los personajes se ven atrapados en un ciclo de eventos que abarcan varias generaciones, la narrativa entrelaza sus destinos, planteando preguntas sobre el libre albedrío y el destino. Con su atmósfera inquietante y tramas intrincadas, \"Dark\" mantiene a los espectadores al borde de sus asientos mientras desentrañan sus misterios.', 'IW4KjKZQJAw', '/series-misterio/misterio2.png', 2017, NULL, 3, 'Louis Hofmann, Karoline Eichhorn, Michael K. Nielsen, Maja Schöne, Oliver Masucci, Andreas Müller, Lisa Vicari, Dietrich Hollinderbäumer', '/titulos/titulo13.png'),
(83, 'Mindhunter', 'Drama, Crimen, Thriller Psicológico', 'Ambientada en los años 70, \"Mindhunter\" sigue a dos agentes del FBI que, junto a una psicóloga, desarrollan técnicas de perfilación criminal mientras entrevistan a asesinos en serie encarcelados. La serie profundiza en la psicología detrás de los crímenes, explorando la mente de los delincuentes y los efectos que su trabajo tiene en los investigadores. Con una narrativa intensa y personajes complejos, \"Mindhunter\" ofrece una mirada fascinante al nacimiento del estudio del comportamiento criminal.\r\n', 'z5au4VLZjo', '/series-misterio/misterio3.png', 2017, NULL, 2, ' Jonathan Groff, Holt McCallany, Anna Torv, Cameron Britton, Hannah Gross, Joe Tuttle, Stacey Roca', '/titulos/titulo183.png'),
(84, 'Detectives Criminales', 'Crimen, Drama, Misterio', 'La serie sigue a un grupo de detectives en la Unidad de Homicidios de la policía que se enfrenta a casos complejos y desgarradores. Cada episodio muestra la investigación de un asesinato, desentrañando pistas y explorando la psicología detrás de los criminales. Con un enfoque en los métodos de investigación y la dinámica del equipo, \"Detectives Criminales\" ofrece un vistazo intrigante al mundo del crimen y la justicia, manteniendo a los espectadores cautivados con sus giros narrativos y desarrollo de personajes.', 'TbVEuab_Fkw', '/series-misterio/misterio4.png', 2019, NULL, 1, 'David Tennant, Hayley Atwell, Nicholas Pinnock, Lee Ingleby, Claire Rushbrook', '/titulos/titulo184.png'),
(85, 'Sherlock', 'Crimen, Drama, Misterio', '\"Sherlock\" es una adaptación contemporánea de las historias clásicas de Sherlock Holmes, donde el brillante detective y su amigo, el Dr. John Watson, resuelven crímenes en Londres. Con un enfoque moderno y narrativas ingeniosas, la serie combina elementos de suspense y humor, mostrando la relación dinámica entre Holmes y Watson. Cada episodio presenta misterios intrigantes y giros inesperados, mientras explora la mente del icónico detective y su capacidad para deducir verdades ocultas.', 'OyWxUjiSQqA', '/series-misterio/misterio5.png', 2010, NULL, 4, 'Benedict Cumberbatch, Martin Freeman, Mark Gatiss, Rupert Graves, Andrew Scott, Una Stubbs', '/titulos/titulo15.png'),
(86, 'Regreso al Futuro', 'Ciencia Ficción, Aventura, Comedia', 'En esta icónica película, Marty McFly, un adolescente, accidentalmente viaja al pasado en una máquina del tiempo construida por el excéntrico Dr. Emmett Brown. Al llegar a 1955, Marty interfiere en el encuentro de sus padres, poniendo en riesgo su propia existencia. Con la ayuda de Doc, debe asegurarse de que sus padres se enamoren mientras intenta regresar a su tiempo. La película combina humor, aventura y un toque de nostalgia, convirtiéndola en un clásico atemporal.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'q27OhNUzBXk', '/action/action13.png', 1985, '1h 56m', NULL, 'Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson', '/titulos/titulo1.png'),
(87, 'Cars', 'Animación, Aventura, Comedia', 'La historia sigue a Lightning McQueen, un coche de carreras egocéntrico que se pierde en un pequeño pueblo llamado Radiator Springs. Mientras espera para llegar a su gran carrera, aprende lecciones sobre la amistad, la humildad y la importancia de la comunidad. Con la ayuda de los habitantes del pueblo, McQueen descubre que hay más en la vida que solo ganar carreras. La película combina humor, emocionantes carreras y una animación vibrante, haciéndola un favorito entre toda la familia.', 'MVYJn8W57wE', '/aventura/aventure11.png', 2006, '1h 57m', NULL, 'Owen Wilson, Paul Newman, Larry the Cable Guy, Bonnie Hunt, Cheech Marin, Michael Keaton', '/titulos/titulo3.png'),
(88, 'Código Traje Rojo\r\n', 'Acción, Ciencia Ficción', 'La trama sigue a un grupo de héroes que, tras un cataclismo global, deben enfrentarse a una amenaza inminente. Equipados con trajes de alta tecnología, estos guerreros luchan para proteger lo que queda de la humanidad. Mientras enfrentan desafíos y revelan secretos, la lealtad y la valentía son puestas a prueba. La película mezcla acción intensa con elementos de ciencia ficción, creando un espectáculo visual emocionante que explora la lucha por la supervivencia en un mundo devastado.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '6PskgH-wxgk', '/aventura/aventure12.png', 2013, '1 hora y 30 minutos', NULL, 'Steven Seagal, Rob Van Damme, Aisha Tyler', '/titulos/titulo4.png'),
(89, 'The Amazing Spider-Man\r\n', 'Acción, Aventura, Ciencia Ficción', 'En esta reinvención del clásico personaje, Peter Parker, un joven estudiante, descubre sus habilidades arácnidas tras ser mordido por una araña radiactiva. Mientras investiga la misteriosa desaparición de sus padres, debe enfrentar al villano Lizard, que representa una amenaza para Nueva York. La película mezcla acción trepidante con temas de identidad y responsabilidad, explorando cómo Peter acepta su destino como Spider-Man. La historia está marcada por su enfoque emocional y el desarrollo de los personajes, haciendo de esta versión un éxito entre los fanáticos.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'XmR5HlEPYiw', '/action/action11.png', 2012, '2 horas y 16 minutos', NULL, 'Andrew Garfield, Emma Stone, Rhys Ifans, Martin Sheen', '/titulos/titulo5.png'),
(90, 'Beethoven\r\n', 'Comedia, Familiar', 'La película sigue las travesuras de Beethoven, un travieso y adorable perro de San Bernardo que llega a la familia Newton. Mientras los Newton disfrutan de su nueva mascota, también enfrentan los problemas que Beethoven trae consigo, incluyendo situaciones cómicas y desastrosas. Sin embargo, su lealtad y valentía se ponen a prueba cuando un malvado veterinario intenta capturarlo. Esta película es una mezcla de humor y momentos conmovedores que destacan la importancia de la familia y el amor por las mascotas.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'B9DtypnImbc', '/comedia/comedia12.png', 1992, '1 hora y 27 minutos', NULL, 'Charles Grodin, Bonnie Hunt, Dean Jones, Christopher Castile', '/titulos/titulo6.png'),
(91, 'Garfield', 'Comedia, Familiar, Animación', 'En esta nueva aventura, el icónico gato perezoso, Garfield, se enfrenta a nuevos desafíos y travesuras mientras navega por su vida diaria con su dueño Jon y el perro Odie. A medida que Garfield intenta disfrutar de su vida de pereza y comida, se ve envuelto en situaciones cómicas que ponen a prueba su astucia. La película combina humor, amistad y el característico sarcasmo de Garfield, brindando entretenimiento tanto para los más jóvenes como para los fanáticos de siempre.', '6Ugo7m3xgHU', '/comedia/comedia11.png', 2024, '1h 41m\n', NULL, 'Snoop Dogg, chris pratt, Angus Cloud, Ving Rhames, Hannah Waddingham, Brett Goldstein, Nicholas Hoult, Cecily Strong', '/titulos/titulo8.png'),
(92, 'Oppenheimer\r\n', 'Biografía, Drama, Historia', 'La película narra la vida de J. Robert Oppenheimer, el físico que lideró el proyecto Manhattan, el esfuerzo de Estados Unidos para desarrollar la bomba atómica durante la Segunda Guerra Mundial. A medida que avanza en su carrera, Oppenheimer se enfrenta a dilemas morales y éticos sobre el uso de su invención. Con una narrativa intensa y un enfoque en el costo humano de la ciencia, la película explora las repercusiones de su trabajo en el mundo moderno.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'gMPEbJQun68', '/ciencia-fision/ciencia-fision11.png', 2023, '3 horas', NULL, 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.\n\n', '/titulos/titulo9.png');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `sliderauto`
--

CREATE TABLE `sliderauto` (
  `id` int(11) NOT NULL,
  `background` varchar(50) DEFAULT NULL,
  `titulo` varchar(50) DEFAULT NULL,
  `descripcion` varchar(5000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `sliderauto`
--

INSERT INTO `sliderauto` (`id`, `background`, `titulo`, `descripcion`) VALUES
(17, 'bg/bg22.png', '/titulos/titulo22.png', '\r\nEn Mi Pobre Angelito, el pequeño Kevin McCallister es olvidado en casa por su familia justo antes de las vacaciones de Navidad. Solo en casa, Kevin se da cuenta de que dos torpes ladrones intentan robar en su vecindario, y decide defender su hogar usando ingeniosos y divertidos trucos. Lo que comienza como una aventura termina en una serie de desastres cómicos, mientras Kevin demuestra que no es tan indefenso como parece.'),
(20, '/bg/bg2.png', '/titulos/titulo2.png', 'Un tímido empleado encuentra una misteriosa máscara antigua que lo transforma en un personaje alocado, con poderes impredecibles y una personalidad explosiva. Ahora, con habilidades fuera de control, su vida está a punto de volverse un torbellino de caos y diversión sin límites.'),
(24, 'bg/bg20.png', '/titulos/titulo20.png', '\r\nEn Tonto y Retonto, Lloyd y Harry, dos amigos increíblemente ingenuos y despistados, se embarcan en un viaje épico para devolver un misterioso maletín a su dueña, sin darse cuenta de que están involucrados en una situación mucho más peligrosa de lo que creen. Entre malentendidos y situaciones absurdas, estos dos amigos provocan risas con sus ocurrencias y su torpeza en un viaje donde todo puede salir mal... y seguramente lo hará.'),
(39, 'bg/bg21.png', '/titulos/titulo21.png', '\r\nEn El Planeta de los Simios: Confrontación (2014), los humanos luchan por sobrevivir en un mundo postapocalíptico después de que un virus devastador ha diezmado a la humanidad. Mientras tanto, una creciente civilización de simios inteligentes, liderada por el carismático César, vive en paz en los bosques. Pero cuando ambos grupos se encuentran, la tensión crece, y una frágil paz amenaza con romperse, desencadenando una batalla épica por el control del planeta.'),
(40, '/bg/bg7.png', '/titulos/titulo7.png', 'En un futuro en el que la Tierra está al borde del colapso, un grupo de exploradores espaciales emprende una misión a través de un agujero de gusano en busca de un nuevo hogar para la humanidad. Mientras viajan hacia lo desconocido, enfrentan desafíos científicos, dilemas emocionales y la inmensidad del cosmos, poniendo a prueba sus lazos familiares y su comprensión del tiempo y el espacio.'),
(54, 'bg/bg19.png', '/titulos/titulo19.png', '\r\nEn It, un grupo de niños conocidos como el \"Club de los Perdedores\" se enfrenta a una entidad maligna que toma la forma de Pennywise, un payaso aterrador que se alimenta de sus miedos. En el inquietante pueblo de Derry, donde desaparecen niños cada 27 años, el grupo deberá unir fuerzas para enfrentar sus peores pesadillas y detener a esta criatura antes de que los atrape.'),
(61, '/bg/bg18.png', '/titulos/titulo18.png', '\r\nEn Breaking Bad, Walter White, un profesor de química de secundaria diagnosticado con cáncer, se convierte en fabricante de metanfetaminas para asegurar el futuro de su familia. Asociándose con su exalumno Jesse Pinkman, Walter se adentra en el peligroso mundo del narcotráfico, donde su ingenio y habilidad científica lo transforman de un hombre común en el infame “Heisenberg.” A medida que escala en el mundo criminal, su vida y sus relaciones se desmoronan, llevándolo a decisiones cada vez más oscuras y extremas.'),
(64, 'bg/bg23.png', '/titulos/titulo23.png', '\r\nEn Dragon Ball Super, Goku y sus amigos regresan con nuevas y emocionantes aventuras, enfrentando enemigos de otros universos y alcanzando niveles de poder nunca antes vistos. Tras la paz alcanzada después de la derrota de Majin Buu, Goku se enfrenta a desafíos aún mayores, incluyendo dioses de la destrucción, seres de otros universos y el Torneo de Poder, donde el destino de su universo está en juego. Con transformaciones épicas y batallas al límite, Goku y Vegeta llevan su fuerza más allá para proteger a quienes aman y demostrar que siempre hay un nuevo nivel por alcanzar.'),
(65, '/bg/bg16.png', '/titulos/titulo16.png', '\r\nEn Attack on Titan, la humanidad se encuentra al borde de la extinción, viviendo dentro de enormes murallas que los protegen de los titanes, seres gigantescos y aterradores que devoran personas. Eren Jaeger, junto a sus amigos Mikasa y Armin, se une al ejército para luchar contra estos monstruos después de que su ciudad natal es destruida. En su lucha por sobrevivir, descubrirán oscuros secretos sobre los titanes y el verdadero origen de su encierro, cuestionando quiénes son realmente los enemigos.'),
(69, '/bg/bg17.png', '/titulos/titulo17.png', '\r\nEn Tom y Jerry: El show de 2014, el gato Tom y el ratón Jerry continúan su eterna rivalidad con persecuciones y travesuras clásicas, ahora en episodios cortos y modernos. Con nuevas situaciones y escenarios, los personajes mantienen su humor físico y su ingenio en un estilo actualizado, donde cada episodio es una batalla llena de caos y diversión en la que siempre terminan regresando a su dinámica de enemigos-amigos.'),
(71, '/bg/bg10.png ', '/titulos/titulo10.png', 'En Gravity Falls, los gemelos Dipper y Mabel Pines pasan el verano con su excéntrico tío abuelo Stan en un misterioso pueblo lleno de secretos y criaturas extrañas. Mientras exploran el lugar, descubren un diario lleno de pistas sobre lo sobrenatural y enfrentan aventuras llenas de humor, suspenso y enigmas que podrían cambiarlo todo.'),
(72, '/bg/bg12.png', '/titulos/titulo12.png', 'En Stranger Things, un grupo de amigos en el tranquilo pueblo de Hawkins se ve envuelto en una serie de eventos sobrenaturales cuando uno de ellos desaparece misteriosamente. Mientras buscan respuestas, descubren un mundo oscuro y aterrador llamado el \"Upside Down,\" experimentos secretos del gobierno y una niña con poderes especiales. Enfrentándose a criaturas aterradoras y a peligros desconocidos, la amistad y el coraje serán su única esperanza para sobrevivir.'),
(75, '/bg/bg11.png ', '/titulos/titulo11.png', 'En Hora de Aventura, Finn, un joven aventurero, y su mejor amigo Jake, un perro con poderes mágicos, exploran la tierra postapocalíptica de Ooo. Juntos enfrentan criaturas extrañas, reinos mágicos y dilemas inesperados, en un viaje lleno de humor, amistad y lecciones de vida. Cada aventura los lleva a descubrir más sobre el mundo, sus amigos y ellos mismos.'),
(76, '/bg/bg14.png', '/titulos/titulo14.png', '\r\nEn Rick y Morty, un científico excéntrico y desinhibido llamado Rick Sánchez arrastra a su nieto Morty en aventuras interdimensionales y experimentos peligrosos. Juntos, exploran mundos extraños, se enfrentan a seres cósmicos y desafían las leyes de la realidad misma, mientras lidian con los problemas de la vida cotidiana. Entre humor oscuro y momentos existenciales, Rick y Morty descubren que el universo es tan vasto como absurdo.'),
(82, '/bg/bg13.png ', '/titulos/titulo13.png', '\r\nEn Dark, un tranquilo pueblo alemán llamado Winden se convierte en el centro de un misterio perturbador cuando varios niños desaparecen, revelando una intrincada red de secretos familiares y viajes en el tiempo. A medida que los personajes intentan desentrañar el enigma, descubren que el pasado, presente y futuro están conectados de formas inesperadas, atrapándolos en un ciclo de tragedia y destino.'),
(85, '/bg/bg15.png ', '/titulos/titulo15.png', '\r\nEn Sherlock, el brillante pero excéntrico detective Sherlock Holmes, junto a su fiel amigo y compañero, el Dr. John Watson, resuelve crímenes complejos en el Londres moderno. Con una mente afilada y métodos poco convencionales, Sherlock desentraña misterios que parecen imposibles, enfrentándose a criminales ingeniosos y a su eterno rival, Moriarty. Cada caso es un juego de ingenio y peligro, donde nada es lo que parece.'),
(86, 'bg/bg1.png', 'titulos/titulo1.png', 'Un adolescente común y corriente accidentalmente viaja en el tiempo gracias a un excéntrico científico y su máquina del tiempo, un DeLorean modificado. Ahora, atrapado en el pasado, deberá arreglar el caos que provoca y asegurarse de que sus padres se enamoren... o su propia existencia estará en peligro.'),
(87, '/bg/bg3.png', '/titulos/titulo3.png', '\r\nEn Cars, un autosportista arrogante llamado Lightning McQueen termina accidentalmente en un tranquilo pueblo llamado Radiator Springs. Mientras intenta regresar a la gran carrera, hace nuevos amigos y aprende lecciones sobre la importancia de la amistad, la humildad y disfrutar del viaje, no solo de la meta.'),
(88, '/bg/bg4.png', '/titulos/titulo4.png', '\nUn agente del FBI se ve obligado a trabajar con dos de los ladrones más astutos del mundo en una peligrosa carrera por robar unas antiguas reliquias. Con giros inesperados, traiciones y mucha acción, el \"traje rojo\" se convierte en símbolo de una misión llena de adrenalina y engaños.'),
(89, '/bg/bg5.png', '/titulos/titulo5.png', 'Un joven Peter Parker descubre sus habilidades sobrehumanas después de ser mordido por una araña modificada genéticamente. Mientras explora su nuevo poder, enfrenta la amenaza de un villano inesperado, el Lagarto, mientras intenta equilibrar su vida como estudiante y héroe. Con grandes poderes vienen grandes responsabilidades, y Peter deberá elegir entre salvar a los demás o proteger a sus seres queridos.'),
(90, '/bg/bg6.png', '/titulos/titulo6.png', 'Un torpe pero adorable perro San Bernardo llamado Beethoven llega a la vida de la familia Newton, causando caos y risas con sus travesuras. Mientras conquista a todos con su corazón de oro, también se enfrenta a un peligroso plan que podría poner en riesgo su futuro, llevando a la familia a luchar por mantener a su nuevo amigo.'),
(91, '/bg/bg8.png', '/titulos/titulo8.png', '\r\nEl gato más perezoso y sarcástico del mundo está de regreso en esta nueva aventura animada. Garfield, con su amor insaciable por la lasaña y su desprecio por los lunes, se enfrenta a desafíos inesperados cuando algo disruptivo sacude su vida perfecta. Prepárate para humor, travesuras y, por supuesto, un montón de lasaña.'),
(92, '/bg/bg9.png', '/titulos/titulo9.png', '\r\nEl físico J. Robert Oppenheimer lidera un equipo de científicos en el Proyecto Manhattan, en una carrera contra el tiempo para desarrollar la primera bomba atómica durante la Segunda Guerra Mundial. Pero mientras se acerca al éxito, también enfrenta las consecuencias éticas y personales de haber creado una de las armas más destructivas de la historia.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nombre` varchar(15) DEFAULT NULL,
  `email` varchar(30) DEFAULT NULL,
  `telefono` int(11) DEFAULT NULL,
  `clave` varchar(30) DEFAULT NULL,
  `foto_perfil` varchar(255) DEFAULT 'views/img/perfil/perfil.png'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `nombre`, `email`, `telefono`, `clave`, `foto_perfil`) VALUES
(1, 'pepito', 'pepito@gmail.com', 12312312, '1234', 'views/img/perfil/perfil.png'),
(2, 'uriel zerda', 'uriel2@gmail.com', NULL, '1234', 'views/img/perfil/perfil.png'),
(3, 'jose', 'josepepe@gmail.com', NULL, '1234', 'views/img/perfil/perfil.png'),
(4, 'rafael', 'rafa2@gmail.com', NULL, 'tumama', 'views/img/perfil/perfil.png'),
(5, 'maxi', 'maxi2@gmail.com', NULL, '1234', 'views/img/perfil/perfil.png'),
(6, 'juan', 'juan@gmail.com', NULL, 'juan1234', 'views/img/perfil/perfil.png'),
(7, 'uriel', 'uriel@gmail.com', NULL, '1234', 'views/img/perfil/perfil.png'),
(8, 'patricia', 'patriciachamorro201966@gmail.c', NULL, 'clarodeluz', 'views/img/perfil/perfil.png'),
(10, 'patricia', 'patriciachamorro888@gmail.com', NULL, 'cieloazul', 'views/img/perfil/perfil.png'),
(11, 'katy', 'katyleto@gmail.com', NULL, 'holaluli', 'views/img/perfil/perfil.png'),
(12, 'fernando', 'telacomesdoblada@gmail.com', NULL, 'pija123', 'views/img/perfil/perfil.png'),
(13, 'alfredo guzmán', 'alfreditotocameelpitito34@hotm', NULL, 'situhermanaestasoltera¿porquec', 'views/img/perfil/perfil.png'),
(14, 'alfredo guzmán', 'alfredito34@hotmail.com', NULL, 'telacomessinpretexto', 'views/img/perfil/perfil.png');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `sliderauto`
--
ALTER TABLE `sliderauto`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=93;

--
-- AUTO_INCREMENT de la tabla `sliderauto`
--
ALTER TABLE `sliderauto`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;

--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
